services:
  - type: web
    name: image-captioning-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 600 --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
